// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCURPH5_fqw_ICS5kuy8jPCELUC4WJy9Pw',
    appId: '1:250136692758:web:e239bef5638e6fb4278d37',
    messagingSenderId: '250136692758',
    projectId: 'notes-75fc9',
    authDomain: 'notes-75fc9.firebaseapp.com',
    storageBucket: 'notes-75fc9.appspot.com',
    measurementId: 'G-E7KYE74WDG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcELlOZ06-9Vt_dnQP1rW8C51PU0zKp7s',
    appId: '1:250136692758:android:e360a1affa7f7fc8278d37',
    messagingSenderId: '250136692758',
    projectId: 'notes-75fc9',
    storageBucket: 'notes-75fc9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1kKcgW6Xprf_q4XhLFKjJmrD2OmvSgsQ',
    appId: '1:250136692758:ios:c4ab26ab310a96b1278d37',
    messagingSenderId: '250136692758',
    projectId: 'notes-75fc9',
    storageBucket: 'notes-75fc9.appspot.com',
    iosClientId:
        '250136692758-c413p8mhsrsvarjbmtcg1s7e0somoa08.apps.googleusercontent.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1kKcgW6Xprf_q4XhLFKjJmrD2OmvSgsQ',
    appId: '1:250136692758:ios:c4ab26ab310a96b1278d37',
    messagingSenderId: '250136692758',
    projectId: 'notes-75fc9',
    storageBucket: 'notes-75fc9.appspot.com',
    iosClientId:
        '250136692758-c413p8mhsrsvarjbmtcg1s7e0somoa08.apps.googleusercontent.com',
    iosBundleId: 'com.example.notes',
  );
}
